// tslint:disable: no-magic-numbers
import { MEGADRIVE_BUTTON } from '@src/constants/megadrive6-buttons';
import { Config } from '@src/interfaces';

export const config: Config = {
  version: 1,
  name: 'SEGA Mega Drive 6 button pad',
  images: [
    {
      src: 'img/megadrive6/bg.png',
      notes: 'Base gamepad image',
      zIndex: 1,
    },
  ],
  widgets: [
    {
      type: 'button',
      name: 'Start Button',
      input: MEGADRIVE_BUTTON.START,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 108,
        top: 44,
        width: 24,
        height: 12,
        offsetX: 108,
        offsetY: 44,
      },
    },
    {
      type: 'button',
      name: 'Mode button',
      input: MEGADRIVE_BUTTON.MODE,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 168,
        top: 4,
        width: 44,
        height: 24,
        offsetX: 168,
        offsetY: 4,
      },
    },
    {
      type: 'button',
      name: 'Up button',
      input: MEGADRIVE_BUTTON.UP,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 52,
        top: 32,
        width: 20,
        height: 24,
        offsetX: 52,
        offsetY: 32,
      },
    },
    {
      type: 'button',
      name: 'Down button',
      input: MEGADRIVE_BUTTON.DOWN,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 52,
        top: 60,
        width: 20,
        height: 24,
        offsetX: 52,
        offsetY: 60,
      },
    },
    {
      type: 'button',
      name: 'Left button',
      input: MEGADRIVE_BUTTON.LEFT,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 36,
        top: 48,
        width: 24,
        height: 20,
        offsetX: 36,
        offsetY: 48,
      },
    },
    {
      type: 'button',
      name: 'Right button',
      input: MEGADRIVE_BUTTON.RIGHT,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 64,
        top: 48,
        width: 24,
        height: 20,
        offsetX: 64,
        offsetY: 48,
      },
    },
    {
      type: 'button',
      name: 'A button',
      input: MEGADRIVE_BUTTON.A,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 156,
        top: 60,
        width: 20,
        height: 20,
        offsetX: 156,
        offsetY: 60,
      },
    },
    {
      type: 'button',
      name: 'B button',
      input: MEGADRIVE_BUTTON.B,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 176,
        top: 52,
        width: 20,
        height: 20,
        offsetX: 176,
        offsetY: 52,
      },
    },
    {
      type: 'button',
      name: 'C button',
      input: MEGADRIVE_BUTTON.C,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 196,
        top: 44,
        width: 20,
        height: 20,
        offsetX: 196,
        offsetY: 44,
      },
    },
    {
      type: 'button',
      name: 'X button',
      input: MEGADRIVE_BUTTON.X,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 148,
        top: 40,
        width: 16,
        height: 16,
        offsetX: 148,
        offsetY: 40,
      },
    },
    {
      type: 'button',
      name: 'Y button',
      input: MEGADRIVE_BUTTON.Y,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 168,
        top: 32,
        width: 16,
        height: 16,
        offsetX: 168,
        offsetY: 32,
      },
    },
    {
      type: 'button',
      name: 'Z button',
      input: MEGADRIVE_BUTTON.Z,
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 188,
        top: 28,
        width: 16,
        height: 16,
        offsetX: 188,
        offsetY: 28,
      },
    },
  ],
};
