// tslint:disable: no-magic-numbers
import { Config } from '../constants';

export const config: Config = {
  version: 1,
  name: 'SEGA Mega Drive 6 button pad',
  images: [
    {
      src: 'img/megadrive6/bg.png',
      notes: 'Base gamepad image',
      zIndex: 1,
    },
  ],
  widgets: [
    {
      type: 'button',
      name: 'Start Button',
      input: {
        type: 'button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        button: 9,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 108,
        top: 44,
        width: 24,
        height: 12,
        offsetX: 108,
        offsetY: 44,
      },
    },
    {
      type: 'button',
      name: 'Mode button',
      input: {
        type: 'button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        button: 8,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 168,
        top: 4,
        width: 44,
        height: 24,
        offsetX: 168,
        offsetY: 4,
      },
    },
    {
      type: 'button',
      name: 'Up button',
      input: {
        type: 'axis-as-button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        axis: 1,
        min: -Infinity,
        max: -0.5,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 52,
        top: 32,
        width: 20,
        height: 24,
        offsetX: 52,
        offsetY: 32,
      },
    },
    {
      type: 'button',
      name: 'Down button',
      input: {
        type: 'axis-as-button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        axis: 1,
        min: 0.5,
        max: Infinity,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 52,
        top: 60,
        width: 20,
        height: 24,
        offsetX: 52,
        offsetY: 60,
      },
    },
    {
      type: 'button',
      name: 'Left button',
      input: {
        type: 'axis-as-button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        axis: 0,
        min: -Infinity,
        max: -0.5,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 36,
        top: 48,
        width: 24,
        height: 20,
        offsetX: 36,
        offsetY: 48,
      },
    },
    {
      type: 'button',
      name: 'Right button',
      input: {
        type: 'axis-as-button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        axis: 0,
        min: 0.5,
        max: Infinity,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 64,
        top: 48,
        width: 24,
        height: 20,
        offsetX: 64,
        offsetY: 48,
      },
    },
    {
      type: 'button',
      name: 'A button',
      input: {
        type: 'button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        button: 2,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 156,
        top: 60,
        width: 20,
        height: 20,
        offsetX: 156,
        offsetY: 60,
      },
    },
    {
      type: 'button',
      name: 'B button',
      input: {
        type: 'button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        button: 1,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 176,
        top: 52,
        width: 20,
        height: 20,
        offsetX: 176,
        offsetY: 52,
      },
    },
    {
      type: 'button',
      name: 'C button',
      input: {
        type: 'button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        button: 5,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 196,
        top: 44,
        width: 20,
        height: 20,
        offsetX: 196,
        offsetY: 44,
      },
    },
    {
      type: 'button',
      name: 'X button',
      input: {
        type: 'button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        button: 3,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 148,
        top: 40,
        width: 16,
        height: 16,
        offsetX: 148,
        offsetY: 40,
      },
    },
    {
      type: 'button',
      name: 'Y button',
      input: {
        type: 'button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        button: 0,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 168,
        top: 32,
        width: 16,
        height: 16,
        offsetX: 168,
        offsetY: 32,
      },
    },
    {
      type: 'button',
      name: 'Z button',
      input: {
        type: 'button',
        pad: '6B controller (Vendor: 0ca3 Product: 0024)',
        button: 4,
      },
      images: {
        src: 'img/megadrive6/pressed.png',
        zIndex: 2,
        left: 188,
        top: 28,
        width: 16,
        height: 16,
        offsetX: 188,
        offsetY: 28,
      },
    },
  ],
};
