// tslint:disable: no-magic-numbers

const pressed = {
  src: 'img/gba/pressed.png',
  zIndex: 2,
};

export const IMG_GBA_BUTTON = {
  BASE: {
    src: 'img/gba/bg.png',
    notes: 'Base gamepad image',
    zIndex: 1,
  },
  SELECT: {
    ...pressed,
    left: 42,
    top: 90,
    offsetX: 42,
    offsetY: 90,
    width: 6,
    height: 6,
  },
  START: {
    ...pressed,
    left: 42,
    top: 78,
    offsetX: 42,
    offsetY: 78,
    width: 6,
    height: 6,
  },
  UP: {
    src: 'img/gba/vertical.png',
    zIndex: 2,
    left: 24,
    top: 33,
    width: 12,
    height: 12,
  },
  DOWN: {
    src: 'img/gba/vertical.png',
    zIndex: 2,
    left: 24,
    top: 51,
    width: 12,
    height: 12,
    offsetY: 18,
  },
  LEFT: {
    src: 'img/gba/horizontal.png',
    zIndex: 2,
    left: 15,
    top: 42,
    width: 15,
    height: 12,
  },
  RIGHT: {
    src: 'img/gba/horizontal.png',
    zIndex: 2,
    left: 30,
    top: 42,
    width: 15,
    height: 12,
    offsetX: 15,
  },
  A: {
    ...pressed,
    left: 204,
    top: 39,
    offsetX: 204,
    offsetY: 39,
    width: 15,
    height: 15,
  },
  B: {
    ...pressed,
    left: 183,
    top: 45,
    offsetX: 183,
    offsetY: 45,
    width: 15,
    height: 15,
  },
  L: {
    ...pressed,
    left: 6,
    top: 3,
    width: 39,
    height: 18,
    offsetX: 6,
    offsetY: 3,
  },
  R: {
    ...pressed,
    left: 186,
    top: 3,
    width: 39,
    height: 18,
    offsetX: 186,
    offsetY: 3,
  },
};
