// tslint:disable: no-magic-numbers

const pressed = {
  src: 'img/sufami/pressed.png',
  zIndex: 2,
  width: 20,
  height: 20,
};

export const IMG_SUFAMI_BUTTON = {
  BASE: {
    src: 'img/sufami/bg.png',
    notes: 'Base gamepad image',
    zIndex: 1,
  },
  SELECT: {
    ...pressed,
    left: 96,
    top: 72,
    offsetX: 96,
    offsetY: 72,
  },
  START: {
    ...pressed,
    left: 120,
    top: 72,
    offsetX: 120,
    offsetY: 72,
  },
  UP: {
    src: 'img/sufami/up-down.png',
    zIndex: 2,
    left: 44,
    top: 48,
    width: 16,
    height: 28,
  },
  DOWN: {
    src: 'img/sufami/up-down.png',
    zIndex: 2,
    left: 44,
    top: 76,
    width: 16,
    height: 28,
    offsetY: 28,
  },
  LEFT: {
    src: 'img/sufami/left-right.png',
    zIndex: 2,
    left: 24,
    top: 68,
    width: 28,
    height: 16,
  },
  RIGHT: {
    src: 'img/sufami/left-right.png',
    zIndex: 2,
    left: 52,
    top: 68,
    width: 28,
    height: 16,
    offsetX: 28,
  },
  A: {
    ...pressed,
    left: 200,
    top: 68,
    offsetX: 200,
    offsetY: 68,
  },
  B: {
    ...pressed,
    left: 180,
    top: 88,
    offsetX: 180,
    offsetY: 88,
  },
  X: {
    ...pressed,
    left: 180,
    top: 48,
    offsetX: 180,
    offsetY: 48,
  },
  Y: {
    ...pressed,
    left: 160,
    top: 68,
    offsetX: 160,
    offsetY: 68,
  },
  L: {
    ...pressed,
    left: 28,
    top: 12,
    width: 60,
    height: 16,
    offsetX: 28,
    offsetY: 12,
  },
  R: {
    ...pressed,
    left: 152,
    top: 12,
    width: 60,
    height: 16,
    offsetX: 152,
    offsetY: 12,
  },
};
